### ISSUE TITLE
Shots won't register / Glitchy game overall

### ISSUE THREAD

**Issue by sokably** [SurvivReloaded/survivreloaded-server#38]
My shots register 20% of the time. There's random people everywhere that disappear mid game and rounds don't start or restart like they should. Good loot is too common and should be way more uncommon. Roofs don't collapse and club isn't fully developed so I really don't know the point of adding it into the game yet. There's no toilet or slowing down when shooting a gun. You can't OC, it should the other gun instead of the gun you're trying to OC. It's glitchy/laggy. (Just some criticism)

**Comment by EagleEye2010** [comment]
One way to reduce glitch would be to interpolate players. Let's say we have the server sending in a new frame 20 times per second (i.e. 20 FPS). This would look somewhat slow to our human eyesight. The easy trail to take is to just go with it and update the players, bullets, and objects whenever the server tells the client to. A better way would be to simply take the frame, and move the player that divided by 3, so it _appears_ to be 60fps or what but it is really not. When the server sends in another request, it should automatically reset because the server should be in control of everything. Hope this helps!

**Comment by hsanger** [comment]
The fix for this ended up being enabling continuous collision detection for bullets.
